//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AVIMux_GUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AVIMUX_GUI_DIALOG           102
#define IDS_FILEISMP3CBR                102
#define IDS_FILEISMP3VBR                103
#define IDS_INFORMATION                 104
#define IDS_WARNING                     105
#define IDS_ERROR                       106
#define IDS_COULDBECBR                  107
#define IDS_CONFIRMATION                108
#define IDS_NOVIDEOSOURCE               109
#define IDS_OVER2GBONLYODML             110
#define IDS_NOVIDEOSOURCECHOSEN         111
#define IDS_FILETYPENOTSUPPORTED        112
#define IDS_COULDNOTAPPENDFILE          113
#define IDS_THISISNOAVI                 114
#define IDS_COULDNOTOPENOUTPUTFILE      115
#define IDS_REALLYCLEARALL              116
#define IDS_OVER4GBONLYNTFS             117
#define IDS_NOAVIMUXFILE                118
#define IDS_CREATEDWITHNEWERVERSION     119
#define IDS_AUDIOSOURCECORRUPT          120
#define IDS_SETAUDIODELAY               121
#define IDS_EXTRACTMP3                  122
#define IDS_EXTRACTWAV                  123
#define IDS_EXTRACTAC3                  124
#define IDS_FRAMENBRTOOHIGH             125
#define IDS_THISISNOKEYFRAME            126
#define IDS_ADD                         127
#define IDR_MAINFRAME                   128
#define IDS_REMOVE                      128
#define IDS_CHANGE                      129
#define IDS_EXTRACTM2F2                 130
#define IDS_M2F2READERROR               131
#define IDS_M2F2CRC                     132
#define IDS_VIDEOSOURCECURRUPT          133
#define IDS_FILE                        134
#define IDS_SOURCE                      135
#define IDR_SOURCEFILEMENU              136
#define IDS_VIDEOINFORMATION            136
#define IDD_SPLITPOINTS                 137
#define IDS_VI_AVITYPE                  137
#define IDS_VI_STANDARD                 138
#define IDR_SPLITPOINTLISTMENU          139
#define IDS_VI_OPENDML                  139
#define IDD_ADDSPLITPOINTDLG            140
#define IDS_VI_RESOLUTION               140
#define IDS_VI_FRAMERATE                141
#define IDR_AUDIOSTREAMSMENU            142
#define IDS_VI_NBROFFRAMES              142
#define IDS_VI_SIZEOFVIDEO              143
#define IDS_VI_VIDEODATARATE            144
#define IDS_VI_AUDIOSTREAMS             145
#define IDS_VI_AUDIOID                  146
#define IDS_VI_AUDIOSTREAM              147
#define IDS_VI_BITRATE                  148
#define IDS_VI_SAMPLINGRATE             149
#define IDD_VIDEOINFO                   150
#define IDS_VI_CHANNELS                 150
#define IDS_VI_GRANULARITY              151
#define IDR_VIDEOINFOMENU               151
#define IDS_VI_AUDIOSTREAMSIZE          152
#define IDD_SETFRAMERATE                152
#define IDS_VI_AUDIOSTREAMCHUNKS        153
#define IDD_SETFLAGS                    153
#define IDS_VI_CHUNKSALTOGETHER         154
#define IDD_OPENFILEOPTIONS             154
#define IDS_VI_HYBRIDE                  155
#define IDD_SAVEAVIOPTIONS              155
#define IDD_SETOUTPUTOPTIONS            155
#define IDS_VI_VIDEOSTREAM              156
#define IDS_VI_FRWRITTENBYIDIOT         157
#define IDS_VI_STREAMLENGTH             158
#define IDR_LANGUAGES                   158
#define IDS_VI_FRAMES                   159
#define IDD_RIFFCHUNKTREEDLG            159
#define IDS_VI_OPENDMLINDEX             160
#define IDR_SUBTITLEMENU                160
#define IDS_VI_SUPERINDEXENTRIES        161
#define IDD_CHAPTERDIALOG               161
#define IDS_VI_ENTRY                    162
#define IDS_VI_STREAM                   163
#define IDS_VI_REALVALUE                164
#define IDS_VI_DWDURATION               165
#define IDD_EBMLTREE_DLG                165
#define IDS_VI_DEFECTIVE                166
#define IDB_BITMAP1                     166
#define IDS_VI_KEYFRAMES                167
#define IDS_VI_DELTAFRAMES              168
#define IDS_VI_DROPPEDFRAMES            169
#define IDS_VI_BICOMPRESSION            170
#define IDS_VILB_REPAIRODML             171
#define IDS_VILB_NOREPAIRS              172
#define IDS_APPLYREPAIRS                173
#define IDS_VILB_REPAIRFRAMERATE        174
#define IDS_VILB_SETFRAMERATE           176
#define IDS_FILEALREADYINUSE            177
#define IDS_VILB_FLAGSSET               178
#define IDS_CANTOPENMP3                 179
#define IDS_VILB_SETMAHFLAGS            180
#define IDS_VERSION                     181
#define IDS_VERSION_INFO                182
#define IDS_VILB_CHUNKSIZES             183
#define IDS_VILB_OVER                   184
#define IDS_VILB_UPTO                   185
#define IDS_ADD_ADVANCEDOPTIONS         186
#define IDS_CLEARALL                    187
#define IDS_NOTENOUGHSPACE              188
#define IDS_READY                       189
#define IDS_EXISTINGFILES               190
#define IDS_CONTINUE                    191
#define IDS_CRAPAC3DATA                 192
#define IDS_NOPERCENT_D                 193
#define IDS_EXTRACTDTS                  194
#define IDS_ODML3AUDIO                  199
#define IDS_VI_DWTOTALFRAMESWRITTENBYIDIOT 200
#define IDS_VILB_TOTALFRAMES            201
#define IDS_VILB_REALFRAMESINRIFF       202
#define IDS_VILB_SBS                    203
#define IDS_VILB_SUBTITLES              204
#define IDS_VILB_SUBTITLE               205
#define IDS_VSLB_INFO                   206
#define IDS_MBYTE                       207
#define IDS_TOOMANYSTRFORSTDAVI         209
#define IDS_LANGUAGE                    210
#define IDS_COULDNTMERGESUBS            211
#define IDC_SOURCEFILELIST              1000
#define IDC_OUTPUTOPTIONS               1003
#define IDC_SETFALGS_RESET              1003
#define IDC_AVAILABLEAUDIOSTREAMS       1004
#define IDC_AVAILABLEVIDEOSTREAMS       1005
#define IDC_RECLISTS                    1006
#define IDC_AUDIOINTERLEAVE             1007
#define IDC_PRELOAD                     1008
#define IDC_MAXFILESIZE                 1009
#define IDC_OPENDML                     1010
#define IDC_START                       1019
#define IDC_STOP                        1022
#define IDC_PROGBAR                     1025
#define IDC_PROGCTRL                    1025
#define IDC_FORMAT                      1026
#define IDC_DESTFILE                    1027
#define IDC_FRAMES                      1028
#define IDC_MAXFRAMES                   1038
#define IDC_ADDAVILIST                  1042
#define IDC_SPLITPOINTLIST              1052
#define IDC_MAXSIZE_EXTENDED            1053
#define IDC_NEWSPLITPOINT               1054
#define IDC_ALLOWDELTA                  1055
#define IDC_USESPLITPOINTLIST           1056
#define IDC_AVOIDSEEKOPS                1057
#define IDC_USEMAXSIZE                  1062
#define IDC_LOAD                        1064
#define IDC_DELAY                       1065
#define IDC_FPS                         1066
#define IDC_MAKEIDX1                    1067
#define IDC_LEGACYPROGRESS              1072
#define IDE_VIDEOINFORMATION            1077
#define IDC_APPLYREPAIRS                1078
#define IDC_NEWFRAMERATE                1079
#define IDR_FR_FPS                      1084
#define IDR_FR_MSPF                     1085
#define IDR_FR_NSPF                     1086
#define IDC_HASINDEX                    1087
#define IDC_MUSTUSEINDEX                1088
#define IDC_ISINTERLEAVED               1089
#define IDC_TRUSTCKTYPE                 1090
#define IDC_WASCAPTUREFILE              1091
#define IDC_COPYRIGHTED                 1092
#define IDC_OFO_AVI_IGNORECHUNKS        1093
#define IDC_OFO_AVI_IGNOREKBYTE         1094
#define IDC_OFO_AVI_TRYTOREPAIRLARGECHUNKS 1095
#define IDC_OFO_M2F2CRCCHECK            1096
#define IDC_OFO_MP3_CHECKCBRALWAYS      1097
#define IDC_OFO_MP3_CHECKCBRASK         1098
#define IDC_OFO_MP3_CHECKCBRNEVER       1099
#define IDC_OFO_AVI_FORCEMP3VBR         1100
#define IDC_OFO_AVI_REPAIRDX50          1106
#define IDC_OFO_CONCAT_ALLOWCRAPAC3     1108
#define IDC_AI_KB                       1108
#define IDC_AI_FRAMES                   1109
#define IDC_NO_AUDIO                    1111
#define IDC_PROTOCOL                    1113
#define IDC_MAXFILES                    1114
#define IDC_USEMAXFILES                 1115
#define IDC_OFO_MP3_RESULTDLG           1116
#define IDC_USENUMBERING                1117
#define IDC_ALL_AUDIO                   1118
#define IDC_AVAILABLETEXTSTREAMS        1119
#define IDC_NO_SUBTITLES                1120
#define IDC_ALL_SUBTITLES               1121
#define IDC_DEFAULT_AUDIO               1122
#define IDC_DEFAULT_AUDIO_NUMBER        1123
#define IDC_STDI_RIFF                   1125
#define IDC_STDI_FRAMES                 1126
#define IDC_STDI_NBROFFRAMES            1127
#define IDC_ODML_SETTINGS               1128
#define IDC_SFO_ODML_SETTINGS           1128
#define IDC_SUBNAME                     1129
#define IDC_STDI_AUTO                   1130
#define IDS_MAIN_OPENFILES              1131
#define IDS_MAIN_AUDIO                  1134
#define IDS_MAIN_SUBTITLES              1135
#define IDS_MAIN_PROTOCOL               1136
#define IDS_MAIN_SUBNAME                1137
#define IDS_MAIN_PROGRESS               1138
#define IDS_MAIN_PRG_DESTFILE           1146
#define IDS_MAIN_PRG_FRAMES             1147
#define IDS_MAIN_PRG_PROGRESS           1150
#define IDS_MAIN_PRG_LEGIDX             1151
#define IDC_ASP_NEWPART                 1152
#define IDC_OFO_AVIFILES                1153
#define IDC_OFO_MP3FILES                1154
#define IDC_OFO_M2F2FILES               1155
#define IDC_OFO_JOINAVIS                1156
#define IDC_SFO_OPTIONS                 1157
#define IDC_SFO_O_AVISTRUCTURE          1158
#define IDC_SFO_O_SPLIT                 1159
#define IDC_SFO_STDIDXPERSTREAM         1160
#define IDC_SAUDIOINTERLEAVE            1161
#define IDC_SPRELOAD                    1162
#define IDC_SFO_FRAMES                  1163
#define IDC_SFO_OSP_FRAMES              1164
#define IDC_SFO_O_AVISTRUCTURE2         1165
#define IDC_SAHF_FLAGS                  1166
#define IDC_SFR_UNIT                    1167
#define IDC_TREE1                       1168
#define IDC_BUTTON1                     1169
#define IDS_MAIN_AUDIONAME              1170
#define IDC_AUDIONAME                   1171
#define IDS_MAIN_AUDIODELAY             1172
#define IDC_MP3CBRFRAMEMODE             1174
#define IDC_ENHLIST                     1176
#define IDC_PROGRESS_LIST               1178
#define IDC_ABOUTBOX_LABEL              1184
#define IDC_AUTHOR                      1185
#define IDC_VIDEOSTRETCHFACTOR          1186
#define IDC_VIDEOSTRETCHFACTORLABEL     1187
#define IDC_TITLE                       1188
#define IDC_TITLELABEL                  1189
#define IDC_SFO_O_MKVOPTIONS            1190
#define IDC_SFO_O_MKVPAGE1              1190
#define IDC_MKV_LACE                    1191
#define IDC_ESPLITPOINT                 1192
#define IDC_IAVI_Label                  1192
#define IDC_ADD                         1193
#define IDC_IMKV_Label                  1193
#define IDC_SFO_O_MKVOPTIONS2           1194
#define IDC_SFO_O_MKVPAGE2              1194
#define IDC_SFO_I_GENERAL               1195
#define IDC_GEN_CHAPTERS                1196
#define IDC_SFO_O_GENERAL               1197
#define IDC_MAKESUBCHAPTER              1198
#define IDC_SFO_O_MKVOPTIONS3           1198
#define IDC_SFO_O_MKVPAGE3              1198
#define IDC_SAVEAS                      1199
#define IDC_BUTTON3                     1200
#define IDC_CH_FROMFILENAMES            1201
#define IDC_CH_IMPORT                   1202
#define IDC_OFO_CHAPTERS                1203
#define IDC_AUDIOTREE                   1204
#define IDC_STDOUTPUTFORMATS            1205
#define IDC_1STTIMESTAMP                1207
#define IDC_1STTIMESTAMP_LABEL          1208
#define IDC_AC3FRAMECOUNT               1210
#define IDC_AC3FRAMECOUNT_SPIN          1211
#define IDC_AC3FRAMECOUNT_LABEL         1212
#define IDC_OUTPUTRESOLUTION_LABEL      1213
#define IDC_OUTPUTRESOLUTION            1214
#define IDC_DONTWRITEBLOCKSIZE          1216
#define IDC_STDOUTPUTFORMAT_LABEL       1218
#define IDC_CLUSTERSIZE_LABEL           1219
#define IDC_CLUSTERSIZE                 1220
#define IDC_CLUSTERSIZE_SPIN            1221
#define IDC_MKV_LACESIZE                1223
#define IDC_MKV_LACESIZE_SPIN           1225
#define IDC_CLUSTERTIME_LABEL           1226
#define IDC_CLUSTERTIME                 1227
#define IDC_CLUSTERTIME_SPIN            1228
#define IDC_MKV_PREVSIZE                1229
#define IDC_MKV_POSITION                1230
#define IDC_1STCL_30sec                 1231
#define IDC_RADIO_AVI                   1233
#define IDC_RADIO_OUTPUT_AVI            1233
#define IDC_RADIO_GENERAL               1234
#define IDC_RADIO_OUTPUT_GENERAL        1234
#define IDC_RADIO_MKV                   1235
#define IDC_RADIO_OUTPUT_MKV            1235
#define IDC_DELETE                      1236
#define IDC_RADIO_INPUT_AVIMP3          1236
#define IDC_RADIO_INPUT_MKV             1237
#define IDC_MKV_AC3FRAMESPERBLOCK       1238
#define IDC_MKV_AC3FRAMESPERBLOCK_SPIN  1239
#define IDC_MKV_AC3FRAMESPERBLOCK_LABEL 1240
#define IDC_LACESTYLE                   1241
#define IDC_IMP3_ASK                    1242
#define IDC_IMP3_CHECKALWAYS            1243
#define IDC_IMP3_CHECKNEVER             1244
#define IDC_IMP3_DISPRESULT             1245
#define IDC_IMP3_LABEL                  1246
#define IDC_IAVI_IGNORECHUNKS_LABEL     1247
#define IDC_IAVI_IGNOREKBYTE            1248
#define IDC_IAVI_TRYTOREPAIRLARGECHUNKS 1249
#define IDC_IAVI_FORCEMP3VBR            1250
#define IDC_IAVI_REPAIRDX50             1251
#define IDC_IM2F2_LABEL                 1252
#define IDC_IM2F2_CRCCHECK              1253
#define IDC_IMKV_CHAPTERS_LABEL         1254
#define IDC_IMKV_CH_IMPORT              1255
#define IDC_IMKV_CH_FROMFILENAMES       1256
#define IDC_I_CH_FROMFILENAMES          1256
#define IDC_OVERLAPPED                  1257
#define IDC_STREAM_LNG                  1258
#define IDC_RADIO_INPUT_GENERAL         1258
#define IDC_MKV_DISPWH                  1259
#define IDC_LACEEXCEPTIONFORMATSPIN     1261
#define IDC_LACEEXCEPTIONFORMAT         1262
#define IDC_USELACINGEXCEPTION          1263
#define IDC_LACEVIDEO                   1264
#define IDC_LACEVIDEO_COUNT             1265
#define IDC_LACEVIDEO_SPIN              1266
#define IDC_FORCEMKV10                  1267
#define IDC_FORCEMKV1                   1267
#define IDC_WRITECUES                   1268
#define IDC_WRITECUES_VIDEO             1269
#define IDC_WRITECUES_AUDIO             1270
#define IDC_WRITECUES_ONLYAUDIOONLY     1271
#define IDC_MKV_CUES                    1272
#define IDC_MKV_LACING                  1273
#define IDC_MKV_CLUSTER                 1274
#define IDC_TCS_MKV                     1275
#define IDC_TCS_MKA                     1276
#define IDC_MKV_PAGE1                   1277
#define IDC_MKV_PAGE2                   1278
#define IDC_TCS_MKV_LABEL               1279
#define IDC_TCS_MKA_LABEL               1280
#define IDC_2ndCopieOfTracks            1281
#define IDC_others                      1282
#define IDC_OUTPUT_MKV3_OTHERS          1282
#define IDC_TIMECODESCALE               1283
#define IDC_INDEXINSEEKHEAD             1284
#define IDC_LOGFILE                     1285
#define IDC_ABSOLUTE                    1286
#define IDC_MKV_PAGE3                   1286
#define IDC_RELATIVE                    1287
#define IDC_FORCEMKV2                   1287
#define IDC_RIFFAVISIZE                 1288
#define IDC_RIFFAVISIZE_LABEL           1289
#define IDC_RIFFAVISIZE_UNIT            1290
#define IDC_CHAPTERTREE                 1291
#define IDC_SFO_ALLOWUNBUFFEREDREAD     1293
#define IDC_SFO_ALLOWUNBUFFEREDWRITE    1294
#define IDC_STATUSLINE                  1296
#define IDC_SAVETREE                    1297
#define IDC_AVI_PAGE1                   1298
#define IDC_AVI_PAGE2                   1299
#define IDC_MP3VBRFRAMECOUNT            1300
#define IDC_MP3VBRFRAMECOUNT_LABEL      1301
#define IDC_FLOATWIDTH                  1305
#define IDC_FLOATWIDTH_SPIN             1306
#define IDC_FLOATWIDTH_LABEL            1307
#define IDC_DTSFRAMECOUNT               1308
#define IDC_DTSFRAMECOUNT_LABEL         1310
#define IDC_SAVE                        1311
#define IDC_FULLEXPAND                  1312
//#define IDC_WAIT                        1312
#define IDC_WAIT_FOR_COMPLETE_TREE      1312
#define IDC_RANDOMIZE_ELEMENT_ORDER     1313
#define IDC_CHAPTER_DISPLAY             1315
#define IDC_CHAPTERDISPLAY_EDIT         1316
#define IDC_CHAPTERDISPLAY_LNG          1317
#define IDC_HAALIMODE                   1319
#define IDC_CHAPTERSEGMENTUID           1321
#define IDC_MOVEHDRL                    1322
#define IDC_NONCLUSTERTOFIRSTSEEKHEAD   1323
#define IDC_MKV_HEADERSIZE_LABEL        1324
#define IDC_MKV_HEADERSIZE              1325
#define IDC_WRITECUES_SUBS              1326
#define IDC_CUES_AUTOSIZE               1328
#define IDC_CUE_MINIMUM_INTERVAL        1329
#define IDC_CUE_MINIMUM_INTERVAL_LABEL  1332
#define IDC_SIZE_PER_STREAM_AND_HOUR    1334
#define IDC_SIZE_PER_STREAM_AND_HOUR_LABEL 1335
#define IDC_CUE_INTERVAL_SETTINGS_LABEL 1336
#define IDC_CUE_TARGET_SIZE_RATIO_LABEL 1338
#define IDC_CUE_TARGET_SIZE_RATIO       1339
#define IDC_CHAPTERUID                  1340
#define IDC_MKV_HARD_LINKING            1343
#define IDC_CHAPTERS_USAGE_LABEL        1344
#define IDC_CHAPTER_EDITOR              1345
#define IDC_CHAPTER_TITLE               1346
#define IDC_CHAPTERUID_LABEL            1348
#define IDC_CHAPTERSEGMENTUID_LABEL     1349
#define IDC_WRITECUES_BLOCKNUMBER       1350
#define IDC_INPUT_OVERLAPPED            1351
#define IDC_HEADER_STRIPPING            1352
#define IDC_MKV3_USE_A_AAC              1353
#define IDC_FONT_LARGER                 1354
#define IDC_FONT_SMALLER                1355
#define ID_LEAVE                        1356
#define ID_INFORMATIONEN                40001
#define IDM_VIDEOINFORMATION            40001
#define ID_TEST                         40002
#define IDM_EXTRACTM2F2                 40002
#define IDM_ADDSPLITPOINT               40003
#define IDM_REMOVESPLITPOINT            40004
#define IDM_EXTRACTWAV                  40005
#define IDM_EXTRACTAC3                  40006
#define IDM_CHANGESPLITPOINT            40007
#define IDM_EXTRACTMP3                  40008
#define IDM_SETDELAY                    40009
#define IDM_M2F2CRC                     40010
#define IDM_REMOVE                      40011
#define IDM_VILB_REPAIRODML             40012
#define IDM_VILB_REPAIRFRAMERATE        40013
#define IDM_VILB_SAVEAS                 40014
#define IDM_VILB_SETFRAMERATE           40015
#define IDM_ADDFILE                     40016
#define IDM_VILB_SETMAHFLAGS            40017
#define IDM_DOADDFILE                   40018
#define IDM_OPENADVANCEDOPTIONS         40019
#define IDM_CLEARALL                    40020
#define IDM_EXTRACTDTS                  40021
#define IDM_VILB_TOTALFRAMES            40022
#define IDM_CLEARALL_NC                 40023
#define IDM_SELAUDIO                    40024
#define IDM_DESELAUDIO                  40025
#define IDM_SELFILE                     40026
#define IDM_ADDAVILIST                  40027
#define IDM_SETOPTION                   40028
#define IDM_DESELFILE                   40029
#define IDM_SETOUTPUTOPTIONS            40030
#define IDM_SETINPUTOPTIONS             40031
#define IDM_SELSUB                      40032
#define IDM_DESELSUB                    40033
#define IDM_DISPLAYSUBNAME              40034
#define IDM_GETNEWSUBNAME               40035
#define IDM_LANG1                       40036
#define IDM_LANG2                       40037
#define IDM_LANG3                       40038
#define IDM_LANG4                       40039
#define IDM_LANG5                       40040
#define IDM_LANG6                       40041
#define IDM_LANG7                       40042
#define IDM_LANG8                       40043
#define IDM_SAVECONFIG                  40044
#define IDM_BUILDRIFFSTATE              40045
#define IDM_DISPLAYAUDIONAME            40046
#define IDM_DISPLAYAUDIODELAY           40047
#define IDM_PROTOCOL                    40048
#define IDM_CONFIGSOURCES               40049
#define IDM_EXTRACTSSA                  40050
#define IDM_STARTMUXING                 40051
#define IDM_DISPDONEDLG                 40052
#define IDM_DISPOVWRTDLG                40053
#define IDM_LANG9                       40054
#define IDM_LANG10                      40055
#define IDM_LANG11                      40056
#define IDM_LANG12                      40057
#define IDM_LANG13                      40058
#define IDM_LANG14                      40059
#define IDM_LANG15                      40060
#define IDM_LANG16                      40061
#define IDM_EXITAFTERWARDS              40062
#define IDM_BYTEACCURACY                40063
#define IDM_SETLANGUAGE                 40064
#define IDM_SAVEPROTOCOLAS              40065
#define IDM_EXTRACT_BINARY              40066
#define IDM_EXTRACT_SUB2TEXT            40067
#define IDM_CHANGESBR                   40068
#define IDM_SETDEFAULTTRACK             40069
#define IDM_SETACTIVESEGMENT            40070
#define IDM_SETACTIVESEGMENT2           40071
#define IDM_SETACTIVESEGMENT3           40072
#define IDM_SETACTIVESEGMENT4           40073
#define IDM_SETACTIVESEGMENT5           40074
#define IDM_SETACTIVESEGMENT6           40075
#define IDM_SETACTIVESEGMENT7           40076
#define IDM_SETACTIVESEGMENT8           40077
#define IDM_SETACTIVESEGMENT9           40078
#define IDM_SETACTIVESEGMENT10          40079
#define IDM_SETACTIVESEGMENT11          40080
#define IDM_SETACTIVESEGMENT12          40081
#define IDM_SETACTIVESEGMENT13          40082
#define IDM_SETACTIVESEGMENT14          40083
#define IDM_SETACTIVESEGMENT15          40084
#define IDM_SETACTIVESEGMENT16          40085
#define IDM_EXTRACT_TOADTS              40086
#define IDM_EXTRACT_OGGVORBIS           40087
#define IDM_IMMED_ADD_AUDIO             40088
#define IDM_ENABLECHAPTER               40089
#define IDM_HIDECHAPTER                 40090
#define IDM_ORDEREDEDITION              40091
#define IDM_DEFAULTEDITION              40092
#define IDM_CHAPTER_COPY                40093
#define IDM_CHAPTER_PASTE_AS_CHILD      40094
#define IDM_CHAPTER_PASTE_AFTER         40095
#define IDM_CHAPTER_DELETE_CLIPBOARD    40096
#define IDM_CHAPTER_PASTE_INTO_NEW_EDITION 40097
#define IDM_CHAPTER_PASTE_EACH_INTO_EDITION 40098
#define IDM_CHAPTER_REINIT_UID_32       40100
#define IDM_CHAPTER_REINIT_UID_64       40101
#define IDM_CHAPTER_COPY_CHILDREN       40102
#define IDM_CHAPTER_NUMERATE            40103
#define IDM_EDITION_TO_CHAPTER          40104
#define ID_Menu                         40105
#define IDM_EBMLTREE                    40106
#define IDM_SELVIDEO                    40108
#define IDM_DESELVIDEO                  40109
#define IDM_WAITFORLOAD                 40110
#define IDM_RIFFTREE                    40111
#define IDM_EXTRACTSRT                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         40112
#define _APS_NEXT_CONTROL_VALUE         1357
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
